image: registry.gitlab.com/pages/hugo:0.55.6
image: rocker/verse:4.1.1

before_script:
  # - apt-get update && apt-get -y install pandoc pandoc-citeproc
  - R -e "install.packages('jsonlite', dependencies = 'Imports')"
  - R -e "install.packages('tibble', dependencies = 'Imports')"
  - R -e "install.packages('xml2', dependencies = 'Imports')"
  - R -e "install.packages('httr', dependencies = 'Imports')"
  - R -e "install.packages('lubridate', dependencies = 'Imports')"
  - R -e "install.packages('magrittr', dependencies = 'Imports')"  
  - R -e "install.packages('stringr', dependencies = 'Imports')"
  - R -e "install.packages('blogdown', dependencies = 'Imports')"
  - R -e "install.packages('yaml', dependencies = 'Imports')"
  - R -e "blogdown::install_hugo(version = '0.55.6')"
  - R -e "options(blogdown.hugo.version = '0.55.6')"
  - Rscript R/fetch.R
  
variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
  - hugo
  except:
  - master

pages:
  script:
  - hugo --environment production
  artifacts:
    paths:
    - public
  only:
  - master



