image: rocker/verse:4.1.1

variables:
  # ssh_deploy_key is defined under Settings > CI/CD Pipelines > Secret Variables.
  temporary_branch: "gitlab-ci-getmd.md"
  GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no -i .ssh/id_rsa-gitlab-ci"
  GIT_STRATEGY: clone

getmd:
  stage: build
  before_script:
    - R -e "install.packages('jsonlite', dependencies = 'Imports')"
    - R -e "install.packages('tibble', dependencies = 'Imports')"
    - R -e "install.packages('xml2', dependencies = 'Imports')"
    - R -e "install.packages('httr', dependencies = 'Imports')"
    - R -e "install.packages('lubridate', dependencies = 'Imports')"
    - R -e "install.packages('magrittr', dependencies = 'Imports')"  
    - R -e "install.packages('stringr', dependencies = 'Imports')"
    - R -e "install.packages('blogdown', dependencies = 'Imports')"
    - R -e "install.packages('yaml', dependencies = 'Imports')"

  script:
    # Prepare git for pushing back to repository.
    - mkdir -pvm 0700 .ssh
    - echo "$ssh_deploy_key" > .ssh/id_rsa-gitlab-ci
    - chmod 0400 .ssh/id_rsa-gitlab-ci
    - git checkout -b "$temporary_branch"
    - git remote set-url origin https://${CI_USERNAME}:${CI_PUSH_TOKEN}@gitlab.com/${CI_PROJECT_NAME}.git
    - git config --global user.email '${GITLAB_USER_EMAIL}'
    - git config --global user.name '${GITLAB_USER_ID}' 
    
    - Rscript R/fetch.R   

    # Push modified .md back to repository
    - git add --all *
    - git commit -m "daily update" || true
    - git push origin "$temporary_branch:$CI_COMMIT_REF_NAME" || true
    
  after_script:
    - rm -Rfv .ssh
