image: rocker/verse:4.0.1

get_md_file:
  stage: build
  before_script:
    - R -e "install.packages('jsonlite', dependencies = 'Imports')"
    - R -e "install.packages('tibble', dependencies = 'Imports')"
    - R -e "install.packages('xml2', dependencies = 'Imports')"
    - R -e "install.packages('httr', dependencies = 'Imports')"
    - R -e "install.packages('lubridate', dependencies = 'Imports')"
    - R -e "install.packages('magrittr', dependencies = 'Imports')"  
    - R -e "install.packages('stringr', dependencies = 'Imports')"
    - R -e "install.packages('blogdown', dependencies = 'Imports')"
    - R -e "install.packages('yaml', dependencies = 'Imports')"

  script:
    - git remote set-url origin https://${CI_USERNAME}:${CI_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
    
    # 在 rocker 的 content/post 下生成 .md 文件
    - Rscript R/fetch.R 

  after_script:
    # push to origin branch
    - git add --all *
    - git commit -m '[skip ci] commit from CI runner'
    - git push origin HEAD:$CI_COMMIT_REF_NAME
    # - git push https://${CI_USERNAME}:${CI_TOKEN}@gitlab.com/${CI_PROJECT_PATH}.git HEAD:refs/heads/main

