image: rocker/verse:4.1.1

variables:
  CI_REPOSITORY_URL: https://$GIT_ACCESS_USER:$GIT_ACCESS_TOKEN@gitlab.com/$CI_PROJECT_PATH.git 

getmd:
  stage: build
  before_script:
    - R -e "install.packages('jsonlite', dependencies = 'Imports')"
    - R -e "install.packages('tibble', dependencies = 'Imports')"
    - R -e "install.packages('xml2', dependencies = 'Imports')"
    - R -e "install.packages('httr', dependencies = 'Imports')"
    - R -e "install.packages('lubridate', dependencies = 'Imports')"
    - R -e "install.packages('magrittr', dependencies = 'Imports')"  
    - R -e "install.packages('stringr', dependencies = 'Imports')"
    - R -e "install.packages('blogdown', dependencies = 'Imports')"
    - R -e "install.packages('yaml', dependencies = 'Imports')"

  script:
    # Prepare git for pushing back to repository.
    - git config --global user.name $GIT_ACCESS_USER
    - git config --global user.email $GIT_ACCESS_EMAIL
    
    # Do something.
    - Rscript R/fetch.R   

    # Push back to repository
    - npm run version -- --prerelease $CI_COMMIT_REF_SLUG
    - git push --follow-tags $CI_REPOSITORY_URL HEAD:$CI_COMMIT_REF_NAME
