baseurl = "https://driller.netlify.app/"
languageCode = "en-us"
title = "DAILY FOR R"
theme = "hugo-xmag"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_cache$", "\\.Rmarkdown$", "\\.knit\\.md$", "\\.utf8\\.md$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
hasCJKLanguage = true
enableEmoji = true

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Archives"
    url = "/archives/"
    weight = 2
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[params]
    description = "A light blog aggregator website for R"
    summary_length = 300
    github_edit = "https://gitlab.com/chuxinyuan/driller/edit/master/content/"
    footer = ""
    
[params.text]
    back = "&larr; Back to Home"
    edit = "Edit this page &rarr;"
    truncated = "&hellip;"
